Node/src/main/java/de/iai/ilcd/model/security/User.java
package de.iai.ilcd.model.security;

import de.iai.ilcd.model.dao.CommonDataStockDao;
import de.iai.ilcd.model.dao.OrganizationDao;
import de.iai.ilcd.model.datastock.AbstractDataStock;
import de.iai.ilcd.security.StockAccessRight;
import de.iai.ilcd.security.StockAccessRightDao;
import de.iai.ilcd.util.SodaUtil;
import org.apache.commons.lang.ObjectUtils;

import javax.persistence.*;
import java.io.Serializable;
import java.util.*;

/**
 * @author clemens.duepmeier
 */
@Entity
@Table(name = "user")
public class User implements ISecurityEntity, Serializable, IUser {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    private String userName;

    @Column(name = "PASSWORD_HASH")
    private String passwordHash;

    @Column(name = "PASSWORD_HASH_SALT")
    private String passwordHashSalt;

    private String firstName;

    private String lastName;

    private String title;

    @Enumerated(EnumType.STRING)
    private Gender gender = null;

    private String institution;

    private String phone;

    private String email;

    private String registrationKey;

    private String dsPurpose;

    private String jobPosition;

    @Column(unique = true)
    private String apiKey;

    @Column(name = "apikeyexpiry")
    private Date apiKeyExpiry;

    @Column(name = "apikeyallowed")
    private Boolean apiKeyAllowed = true;

    @Transient
    private Boolean licenseConditions = false;

    @Column(name = "acceptedAddTerms")
    private Boolean acceptedAdditionalTerms = false;

    @Embedded
    private Address address = new Address();

    @ManyToMany(mappedBy = "users", fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH})
    // Does not contain CascadeType.REMOVE
    private List<UserGroup> groups = new ArrayList<UserGroup>();

    @Basic
    @Column(name = "super_admin_permission")
    private boolean superAdminPermission;

    /**
     * The organization of the user
     */
    @ManyToOne(optional = true)
    @JoinColumn(name = "organization", nullable = true)
    private Organization organization;

    @Basic
    @Column(name = "privacy_policy_accepted")
    private Boolean privacyPolicyAccepted;

    @Basic
    @Column(name = "password_expired")
    private Boolean passwordExpired;


    @ElementCollection(targetClass = String.class)
    @CollectionTable(name = "user_sector", joinColumns = @JoinColumn(name = "User_ID"))
    private List<String> sector = new ArrayList<String>();

    @ElementCollection
    @CollectionTable(name = "user_acceptedaddterms", joinColumns = @JoinColumn(name = "User_ID"))
    @MapKeyColumn(name = "additionalterm")
    @Column(name = "accepted")
    private Map<String, Boolean> acceptedAdditionalTermsMap = new HashMap<String, Boolean>();

    @Basic
    @Column(name = "sector_other")
    private String sectorOther;

    @Column(name = "resetkey")
    private String resetKey;

    @Column(name = "resettimestamp")
    private Date resetTimestamp;


    @Override
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getInstitution() {
        return institution;
    }

    public void setInstitution(String institution) {
        this.institution = institution;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getPasswordHashSalt() {
        return this.passwordHashSalt;
    }

    public void setPasswordHashSalt(String passwordHashSalt) {
        this.passwordHashSalt = passwordHashSalt;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getResetKey() {
        return resetKey;
    }

    public void setResetKey(String resetKey) {
        this.resetKey = resetKey;
    }

    public Date getResetTimestamp() {
        return resetTimestamp;
    }

    public void setResetTimestamp(Date resetTimestamp) {
        this.resetTimestamp = resetTimestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getDisplayName() {
        return this.userName;
    }

    public String getRegistrationKey() {
        return this.registrationKey;
    }

    public void setRegistrationKey(String registrationKey) {
        this.registrationKey = registrationKey;
    }

    public boolean isActivated() {
        return registrationKey == null;
    }

    public List<UserGroup> getGroups() {
        return this.groups;
    }

    protected void setGroups(List<UserGroup> groups) {
        this.groups = groups;
    }

    public String getDsPurpose() {
        return this.dsPurpose;
    }

    public void setDsPurpose(String dspurpose) {
        this.dsPurpose = dspurpose;
    }

    public String getJobPosition() {
        return this.jobPosition;
    }

    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition;
    }

    public Boolean getAcceptedAdditionalTerms() {
        return acceptedAdditionalTerms;
    }

    public void setAcceptedAdditionalTerms(Boolean acceptedAdditionalTerms) {
        this.acceptedAdditionalTerms = acceptedAdditionalTerms;
    }

    public Map<String, Boolean> getAcceptedAdditionalTermsMap() {
        return this.acceptedAdditionalTermsMap;
    }

    public void setAcceptedAdditionalTermsMap(Map<String, Boolean> acceptedAdditionalTermsMap) {
        this.acceptedAdditionalTermsMap = acceptedAdditionalTermsMap;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public Date getApiKeyExpiry() {
        return apiKeyExpiry;
    }

    public void setApiKeyExpiry(Date apiKeyExpiry) {
        this.apiKeyExpiry = apiKeyExpiry;
    }

    public String getApiKeyExpiryString() {
        if (apiKeyExpiry != null) {
            return apiKeyExpiry.toString();
        }
        return "---";
    }

    public Boolean isApiKeyAllowed() {
        return apiKeyAllowed;

    }

    public void setApiKeyAllowed(boolean apiKeyAllowed) {
        this.apiKeyAllowed = apiKeyAllowed;
    }

    /**
     * @param group
     */
    public void addToGroup(UserGroup group) {
        if (!this.groups.contains(group)) {
            this.groups.add(group);
            group.addUser(this);
        }
    }

    public void removeFromGroup(UserGroup group) {
        if (this.groups.contains(group)) {
            this.groups.remove(group);
        }
    }

    public void removeFromAllGroups() {
        List<UserGroup> allGroups = new ArrayList<UserGroup>();
        allGroups.addAll(this.groups);
        for (UserGroup group : allGroups) {
            group.removeUser(this); // this removes the group also locally
        }
    }

    /**
     * Get the organization of this user
     *
     * @return organization of this user
     */
    public Organization getOrganization() {
        return this.organization;
    }

    /**
     * Set the organization of this user
     *
     * @param organization organization of this user to set
     */
    public void setOrganization(Organization organization) {
        if (ObjectUtils.equals(this.organization, organization)) {
            return;
        }
        Organization oldOrg = this.organization;
        this.organization = organization;

        if (oldOrg != null) {
            oldOrg.removeUser(this);
        }

        if (this.organization != null) {
            this.organization.addUser(this);
        }
    }

    public boolean isPrivacyPolicyAccepted() {
        return this.privacyPolicyAccepted != null ? this.privacyPolicyAccepted : false;
    }

    public void setPrivacyPolicyAccepted(boolean privacyPolicyAccepted) {
        this.privacyPolicyAccepted = privacyPolicyAccepted;
    }

    public Boolean isPasswordExpired() {
        return passwordExpired;
    }

    public void setPasswordExpired(Boolean passwordExpired) {
        this.passwordExpired = passwordExpired;
    }

    public Boolean getLicenseConditions() {
        return licenseConditions;
    }

    public void setLicenseConditions(Boolean licenseConditions) {
        this.licenseConditions = licenseConditions;
    }

    public List<String> getSector() {
        return sector;
    }

    public void setSector(List<String> sector) {
        this.sector = new ArrayList<String>(sector);
    }

    public String getSectorAsString() {
        StringBuffer buf = new StringBuffer();
        for (String s : this.sector) {
            if (buf.length() != 0) {
                buf.append(";");
            }
            buf.append(s);
        }

Node/src/main/java/de/iai/ilcd/jmx/ApplicationInfoMBean.java
package de.iai.ilcd.jmx;

public interface ApplicationInfoMBean {
    public String getVersion();

    public String getSchemaVersion();

    public String getNodeId();
}

Node/src/main/java/de/iai/ilcd/security/UserAccessBean.java
package de.iai.ilcd.security;

import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.datastock.IDataStockMetaData;
import de.iai.ilcd.model.security.IUser;
import de.iai.ilcd.model.security.User;
import de.iai.ilcd.webgui.controller.AbstractHandler;
import de.iai.ilcd.webgui.controller.ui.AvailableStockHandler;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.subject.Subject;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.List;
import java.util.stream.Collectors;

/**
 * User access bean
 */
@ManagedBean(name = "user")
@ViewScoped
@Deprecated
public class UserAccessBean extends AbstractHandler { // TODO: rm!!

    /**
     * Serialization ID
     */
    private static final long serialVersionUID = 556220221006512832L;

    /**
     * User object
     */
    private IUser user = SecurityUtil.getCurrentUser();

    /**
     * Determine if user is logged in
     *
     * @return <code>true</code> if user logged in, else <code>false</code>
     */
    public boolean isLoggedIn() {
        Subject currentUser = SecurityUtils.getSubject();
        if (currentUser == null) {
            return false;
        }

        if (currentUser.isAuthenticated() || currentUser.isRemembered()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Determine if user shall be able to enter admin area
     *
     * @return <code>true</code> if access shall be granted, <code>false</code> otherwise
     * @see SecurityUtil#hasAdminAreaAccessRight()
     */
    public boolean hasAdminAreaAccessRight() {
        return SecurityUtil.hasAdminAreaAccessRight();
    }

    /**
     * Determine if user is super admin
     *
     * @return <code>true</code> if super admin access shall be granted, <code>false</code> otherwise
     * @see SecurityUtil#hasSuperAdminPermission()
     */
    public boolean hasSuperAdminPermission() {
        return SecurityUtil.hasSuperAdminPermission();
    }

    /**
     * Determines if user has permission to import data sets into resp. stock.
     *
     * @return
     */
    public boolean hasImportRight(IDataStockMetaData ds) {
        return SecurityUtil.hasImportPermission(ds);
    }

    /**
     * Determines there is any root data stock into which the user can import data sets.
     *
     * @return
     */
    public boolean hasAnyImportRight() {
        AvailableStockHandler stockHandler = new AvailableStockHandler();
        List<IDataStockMetaData> possibleStocks = stockHandler.getRootStocksMeta().stream()
                .filter(stock -> hasImportRight(stock)).collect(Collectors.toList());

        return possibleStocks.size() > 0;
    }

    /**
     * Determine if the current user has dataset detail view (means {@link ProtectionType#EXPORT}) right
     *
     * @param ds data set to check for
     * @return <code>true</code> if dataset detail view right is present, <code>false</code> otherwise
     */
    public boolean hasDatasetDetailRights(DataSet ds) {
        return SecurityUtil.hasExportPermission(ds);
    }

    /**
     * Get the user object for the current user.
     *
     * @return user object
     */
    public IUser getUserObject() {
        return SecurityUtil.getCurrentUser();
    }

    public IUser getUser() {
        return user;
    }

    public void setUser(IUser user) {
        this.user = (User) user;
    }

    public String getUserName() {
        return user.getUserName();
    }

}

Node/src/main/java/de/iai/ilcd/webgui/controller/admin/CustomReportsBean.java
package de.iai.ilcd.webgui.controller.admin;

import de.iai.ilcd.model.common.ReportConfig;
import de.iai.ilcd.service.CustomReportService;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.jsf.FacesContextUtils;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.util.List;

/**
 * The managed bean for retrieving customized reports.
 *
 * @author sarai
 */
@ManagedBean(name = "customReportsBean")
@ApplicationScoped
public class CustomReportsBean {

    private Logger log = LogManager.getLogger(this.getClass());

    private CustomReportService customReportService;

    public CustomReportsBean() {
        WebApplicationContext ctx = FacesContextUtils.getWebApplicationContext(FacesContext.getCurrentInstance());
        this.customReportService = ctx.getBean(CustomReportService.class);
    }

    public List<ReportConfig> getReportConfigs() {
        return customReportService.getReportConfigs();
    }

    /**
     * Checks whether custom reports are enabled.
     *
     * @return true if at least one custom report is set.
     */
    public boolean isCustomReportsEnabled() {
        return (customReportService.getReportConfigs() != null)
                && !customReportService.getReportConfigs().isEmpty();
    }

    /**
     * Executes an SQL query for a report and write result directly to the response
     *
     * @param request  The request to execute
     * @param fileName he desired file name of csv result
     */
    public void executeSQL(final ReportConfig report) {
        try {
            String fileName = new String(report.getFileName()).replace(" ", "_");
            if (report.isTimeStampSuffix()) {
                DateTimeFormatter dtf = DateTimeFormat.forPattern("yyyy-MM-dd_HH-mm");
                fileName += "_" + dtf.print(new DateTime());
            }
            fileName += ".csv";
            if (log.isDebugEnabled())
                log.debug("filename is " + fileName);

            FacesContext facesContext = FacesContext.getCurrentInstance();
            ExternalContext externalContext = facesContext.getExternalContext();
            externalContext.setResponseContentType("text/csv");
            externalContext.setResponseHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");

            customReportService.executeSQLQuery(report, externalContext.getResponseOutputStream());

            facesContext.responseComplete();
        } catch (IOException e) {
            log.error("Error writing response", e);
            if (log.isDebugEnabled())
                e.printStackTrace();
        }
    }

    public CustomReportService getReportService() {
        return this.customReportService;
    }

}

Node/src/main/webapp/admin/addressInfoPanel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:ui="http://java.sun.com/jsf/facelets">
<!-- 
ui:params:
	- countries: country list
	- chosenCountry: chosen country
	- address: address instance
 -->
<ui:param name="backingBean" value="#{contactListHandler}" />
    <p:panel header="#{i18n['admin.user.addrInfo']}">
        <h:panelGrid columns="2">
            <p:outputLabel value="#{i18n['admin.user.country']}:" for="country" />
            <!-- Fix with 150px due to problems with tabs: (usage with orgEntry)
                 dynamic=true for tabs ==> null value set for selectOneMenu
                 dynamic=false ==> selectOneMenu styling bug, set manually -->
            <p:selectOneMenu style="width:150px" id="country" value="#{chosenCountry}" converter="geoAreaConverter" required="#{conf.requireAddressForRegistration}" requiredMessage="#{i18n['common.user.requiredMsg.address']}">
                <f:selectItem itemLabel="#{i18n['common.select.hint']}" itemValue="0" />
                <f:selectItems value="#{countries}" var="country" itemLabel="#{country.name}" itemValue="#{country}" />
            </p:selectOneMenu>
        </h:panelGrid>
        <h:panelGrid columns="4">
            <p:outputLabel value="#{i18n['admin.user.zipCode']}:" for="zipCode" />
            <p:inputText id="zipCode" value="#{address.zipCode}" maxlength="50" size="10"  required="#{conf.requireAddressForRegistration}" requiredMessage="#{i18n['common.user.requiredMsg.address']}"/>
            <p:outputLabel value="#{i18n['admin.user.city']}:" for="city" />
            <p:inputText id="city" value="#{address.city}" maxlength="50" size="30" required="#{conf.requireAddressForRegistration}" requiredMessage="#{i18n['common.user.requiredMsg.address']}"/>
        </h:panelGrid>
        <h:panelGrid>
            <p:outputLabel value="#{i18n['admin.user.streetAddr']}:" for="streetAddr" />
            <p:inputTextarea id="streetAddr" value="#{address.streetAddress}" cols="72" rows="3" maxlength="255"  required="#{conf.requireAddressForRegistration}" requiredMessage="#{i18n['common.user.requiredMsg.address']}"/>
        </h:panelGrid>
    </p:panel>
</ui:composition>

Node/src/main/webapp/admin/manageNodeList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition template="/admin/layout/adminDesign.xhtml">
            <ui:param name="pageTitle" value="#{i18n['admin.node.manageList']}" />
            <ui:define name="content">
                <h:form id="tableForm" prependId="false">
               	
                    <p:commandButton id="deleteBtn"
                                     value="#{i18n['admin.deleteSelected']}"
                                     onclick="PF('confirmDelete').show()"
                                     type="button"
                                     disabled="#{nodeListHandler.nothingSelected}" />
                    <p:confirmDialog message="#{i18n['admin.confirmMsg.deleteSelected']}?"
                                     header="#{i18n['admin.confirmDlg.delete']}"
                                     severity="alert"
                                     widgetVar="confirmDelete">
                        <div class="confirmDlgButtons">
                            <p:commandButton value="#{i18n['admin.cancel']}"
                                             type="button"
                                             onclick="PF('confirmDelete').hide()" />
                            <p:commandButton value="#{i18n['admin.ok']}"
                                             action="#{nodeListHandler.deleteSelected}"
                                             oncomplete="PF('confirmDelete').hide()"
                                             ajax="false"
                                             update="messages nodeTable" />
                        </div>
                    </p:confirmDialog>

                    <ui:include src="/messages.xhtml" />

                    <p:dataTable id="nodeTable"
                                 var="node" 
                                 value="#{nodeListHandler.lazyModel}"
                                 lazy="true"
                                 paginator="true"
                                 rows="15" rowsPerPageTemplate="5,10,15,50"
                                 selection="#{nodeListHandler.selectedNodes}"
                                 paginatorTemplate="{CurrentPageReport} {FirstPageLink}
                                 {PreviousPageLink} {PageLinks} {NextPageLink}
                                 {LastPageLink} {RowsPerPageDropdown} #{i18n['common.list.entriesPerPage']}
                                 (#{nodeListHandler.lazyModel.rowCount} #{i18n['common.list.total']})"
                                 emptyMessage="#{i18n['common.list.noneFound']}">
                        
                        <p:ajax event="rowSelectCheckbox" process="@this" update="@(#deleteBtn)" />
                        <p:ajax event="rowUnselectCheckbox" process="@this" update="@(#deleteBtn)" />
                        <p:ajax event="toggleSelect" process="@this" update="@(#deleteBtn)" />
                                 
                        <p:column style="text-align: center;" selectionMode="multiple" />

                        <p:column headerText="#{i18n['common.node.id']}">
                            <h:link outcome="#{url.node.edit}" value="#{node.nodeId}">
                                <f:param name="nodeId" value="#{node.id}" />
                            </h:link>
                        </p:column>

                        <p:column headerText="#{i18n['common.name']}">
                            <h:outputText value="#{node.name}" />
                        </p:column>

                        <p:column headerText="#{i18n['admin.node.baseURL']}">
                            <h:outputText value="#{node.baseUrl}" />
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Node/src/main/webapp/admin/showNode.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition template="/admin/layout/adminDesign.xhtml">
            <ui:param name="pageTitle" value="#{i18n['admin.node.showUpdateNodeInfo']}" />
            <ui:define name="content">
                <p>#{i18n['common.mandatoryFields']}</p>
                <h:form id="generalForm" prependId="false">

                    <ui:include src="/admin/nodeEntry.xhtml" />

                    <div class="buttonCenter">
                        <p:commandButton value="#{i18n['admin.node.updateNode']}"
                                         action="#{nodeHandler.changeNode}"
                                         update="messages" />
                    </div>
                    <ui:include src="/messages.xhtml" />
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Node/src/main/webapp/admin/validationResults.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<ui:composition>

	<div>
	    <p:outputLabel value="#{i18n['admin.validation.section.results']}" styleClass="margine checkboxalign" />
		<p:commandButton id="exportLogs" value="#{i18n['admin.validation.log.export']}" disabled="#{empty validationHandler.events}" update="logTable,resetEvents" ajax="false">
			<p:dataExporter type="xls" target="logTable" postProcessor="#{validationResultDocumentView.postProcessXLS}" fileName="#{validationHandler.stockName}_log" />
		</p:commandButton>
	    <p:commandButton styleClass="buttonvalid" id="resetEvents" value="#{i18n['admin.validation.log.export.reset']}" actionListener="#{validationHandler.clearEvents}" disabled="#{empty validationHandler.events}" update="logTable,exportLogs,resetEvents,progressBar" >
		</p:commandButton>
	</div>

	<p:importEnum type="de.iai.ilcd.webgui.util.ValidationContext"
		var="ValidationContext" />
	<p:importEnum type="com.okworx.ilcd.validation.common.DatasetType"
		var="ValidationDatasetType" />

	<p:dataTable id="logTable" emptyMessage="" var="event"
		value="#{validationHandler.events}" widgetVar="eventTable"
		tableStyle="width:auto">

		<p:column headerText="#{i18n['admin.validation.log.table.severity']}"
			sortBy="#{event.severity}">
			<h:outputText value="#{event.severity}" />
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.aspect']}"
			sortBy="#{event.aspect}">
			<h:outputText value="#{event.aspect}" />
		</p:column>

		<p:column
			headerText="#{i18n['admin.validation.log.table.reference.name']}"
			sortBy="#{event.reference.name}">
			<h:outputText value="#{event.reference.name}" />
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.type']}"
			sortBy="#{event.reference.datasetType.value}">
			<h:outputText value="#{event.reference.datasetType.value}" />
		</p:column>

		<p:column headerText="UUID" sortBy="#{event.reference.uuid}" exportable="false">
			<c:choose>
				<c:when
					test="#{validationHandler.validationContext==ValidationContext.DATASETS or validationHandler.validationContext==ValidationContext.STOCK}">
					<h:outputLink
						value="#{request.contextPath}#{validationHandler.goToDataset(event.reference.uuid, event.reference.version, event.reference.datasetType)}"
						target="_blank">
						<h:outputText value="#{event.reference.uuid}" />
					</h:outputLink>
				</c:when>
				<c:otherwise>
					<h:outputText value="#{event.reference.uuid}" />
				</c:otherwise>
			</c:choose>
		</p:column>
		
		<p:column visible="false" headerText="UUID">
			<h:outputText value="#{event.reference.uuid}" />
		</p:column>

		<p:column headerText="#{i18n['admin.proc.version']}">
			<h:outputText value="#{event.reference.version}" />
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.processes']}" exportable="false">
			<ui:fragment rendered="#{event.reference.datasetType eq ValidationDatasetType.FLOW}">
				<ui:repeat var="reference" value="#{validationHandler.getRefsToProcessesForFlow(event.reference.uuid)}">
					<h:outputLink
						value="#{request.contextPath}#{validationHandler.goToDataset(reference.uuid, reference.version, reference.datasetType, true)}"
						target="_blank">
						<h:outputText value="#{reference.name}" />
						<br/> 
					</h:outputLink>
				</ui:repeat>
			</ui:fragment>
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.processes']}" visible="false">
				<h:outputText value="#{validationHandler.getRefsAsString(validationHandler.getRefsToProcessesForFlow(event.reference.uuid))}" /> 
		</p:column>

		<p:column headerText="#{i18n['admin.validation.log.table.message']}"
			sortBy="#{event.message}">
			<h:outputText value="#{event.message}" />
		</p:column>
	</p:dataTable>
</ui:composition>
</html>