Node/src/main/java/de/iai/ilcd/model/adapter/dataset/AbstractDatasetAdapter.java
package de.iai.ilcd.model.adapter.dataset;

import de.fzk.iai.ilcd.service.client.impl.vo.dataset.DataSetVO;
import de.fzk.iai.ilcd.service.model.IDataSetListVO;
import de.fzk.iai.ilcd.service.model.IDataSetVO;
import de.iai.ilcd.model.adapter.ClassificationAdapter;
import de.iai.ilcd.model.adapter.LStringAdapter;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public abstract class AbstractDatasetAdapter<T extends DataSetVO, LVO extends IDataSetListVO, VO extends IDataSetVO> {

    @SuppressWarnings("unused")
    private static final Logger logger = LogManager.getLogger(AbstractDatasetAdapter.class);

    private final T dataset;

    protected String language = null;

    protected boolean langFallback = false;

    private AbstractDatasetAdapter(T adapterObject) {
        this.dataset = adapterObject;
    }

    public AbstractDatasetAdapter(T adapterObject, LVO adaptee) {
        this(adapterObject);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    public AbstractDatasetAdapter(T adapterObject, VO adaptee) {
        this(adapterObject);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    private AbstractDatasetAdapter(T adapterObject, String language) {
        this(adapterObject, language, false);
    }

    private AbstractDatasetAdapter(T adapterObject, String language, boolean langFallback) {
        this.dataset = adapterObject;
        this.language = language;
        this.langFallback = langFallback;
    }

    public AbstractDatasetAdapter(T adapterObject, LVO adaptee, String language) {
        this(adapterObject, adaptee, language, false);
    }

    public AbstractDatasetAdapter(T adapterObject, LVO adaptee, String language, boolean langFallback) {
        this(adapterObject, language, langFallback);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    public AbstractDatasetAdapter(T adapterObject, VO adaptee, String language) {
        this(adapterObject, language);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Copy the values from the value <b>AND</b> the list value object
     * to the adapter data set.
     *
     * @param src source object
     * @param dst destination data set
     */
    protected abstract void copyValues(VO src, T dst);

    /**
     * Copy the values from the list value object
     * to the adapter data set
     *
     * @param src source object
     * @param dst destination data set
     */
    protected abstract void copyValues(LVO src, T dst);

    private final void copyValues(IDataSetVO src) {
        this.copyValues((IDataSetListVO) src);
        LStringAdapter.copyLStrings(src.getDescription(), this.dataset.getDescription(), this.language, this.langFallback);
    }

    private final void copyValues(IDataSetListVO src) {

        this.dataset.setUuid(src.getUuidAsString());
        this.dataset.setDataSetVersion(src.getDataSetVersion());
        this.dataset.setPermanentUri(src.getPermanentUri());

        LStringAdapter.copyLStrings(src.getName(), this.dataset.getName(), this.language, this.langFallback);

        try {
            this.dataset.setClassification(new ClassificationAdapter(src.getClassification()));
        } catch (Exception e) {
        }

        this.dataset.setSourceId(src.getSourceId());
        this.dataset.setHref(src.getHref());

        if (src.getDuplicates().size() > 0)
            this.dataset.setDuplicates(src.getDuplicates());
    }

    public T getDataSet() {
        return dataset;
    }

    public boolean isLangFallback() {
        return langFallback;
    }

    public void setLangFallback(boolean langFallback) {
        this.langFallback = langFallback;
    }

}

Node/src/main/java/de/iai/ilcd/model/adapter/dataset/ContactVOAdapter.java
package de.iai.ilcd.model.adapter.dataset;

import de.fzk.iai.ilcd.service.client.impl.vo.dataset.ContactDataSetVO;
import de.fzk.iai.ilcd.service.model.IContactListVO;
import de.fzk.iai.ilcd.service.model.IContactVO;
import de.iai.ilcd.model.adapter.LStringAdapter;

/**
 * Adapter for Contacts
 */
public class ContactVOAdapter extends AbstractDatasetAdapter<ContactDataSetVO, IContactListVO, IContactVO> {

    /**
     * Create adapter for {@link IContactListVO contact list value object}
     *
     * @param adaptee list value object to adapt
     */
    public ContactVOAdapter(IContactListVO adaptee) {
        super(new ContactDataSetVO(), adaptee);
    }

    /**
     * Create adapter for the {@link IContactVO contact value object}
     *
     * @param adaptee value object to adapt
     */
    public ContactVOAdapter(IContactVO adaptee) {
        super(new ContactDataSetVO(), adaptee);
    }

    /**
     * Create adapter for {@link IContactListVO contact list value object}
     *
     * @param adaptee list value object to adapt
     */
    public ContactVOAdapter(IContactListVO adaptee, String language) {
        super(new ContactDataSetVO(), adaptee, language);
    }

    /**
     * Create adapter for {@link IContactListVO contact list value object}
     *
     * @param adaptee list value object to adapt
     */
    public ContactVOAdapter(IContactListVO adaptee, String language, boolean langFallback) {
        super(new ContactDataSetVO(), adaptee, language, langFallback);
    }

    /**
     * Create adapter for the {@link IContactVO contact value object}
     *
     * @param adaptee value object to adapt
     */
    public ContactVOAdapter(IContactVO adaptee, String language) {
        super(new ContactDataSetVO(), adaptee, language);
    }

    /**
     * Create adapter for the {@link IContactVO contact value object}
     *
     * @param adaptee value object to adapt
     */
    public ContactVOAdapter(IContactVO adaptee, String language, boolean langFallback) {
        super(new ContactDataSetVO(), adaptee, language, langFallback);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected void copyValues(IContactListVO src, ContactDataSetVO dst) {
        dst.setEmail(src.getEmail());

        dst.setPhone(src.getPhone());

        dst.setWww(src.getWww());

        LStringAdapter.copyLStrings(src.getShortName(), dst.getShortName(), this.language, this.langFallback);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected void copyValues(IContactVO src, ContactDataSetVO dst) {
        this.copyValues((IContactListVO) src, dst);

        dst.setCentralContactPoint(src.getCentralContactPoint());
        dst.setFax(src.getFax());
    }

}

Node/src/main/java/de/iai/ilcd/model/flow/Flow.java
package de.iai.ilcd.model.flow;

import de.fzk.iai.ilcd.service.client.impl.DatasetTypes;
import de.fzk.iai.ilcd.service.model.IFlowVO;
import de.fzk.iai.ilcd.service.model.common.IMultiLangString;
import de.fzk.iai.ilcd.service.model.enums.TypeOfFlowValue;
import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.common.DataSetType;
import de.iai.ilcd.util.lstring.IStringMapProvider;
import de.iai.ilcd.util.lstring.MultiLangStringMapAdapter;
import org.apache.commons.lang.StringUtils;

import javax.persistence.*;
import java.io.File;
import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static de.iai.ilcd.model.flow.Flow.TABLE_NAME;

/**
 * Common Flow representation
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = TABLE_NAME, uniqueConstraints = @UniqueConstraint(columnNames = {"UUID", "MAJORVERSION", "MINORVERSION", "SUBMINORVERSION"}))
@DiscriminatorColumn(name = "flow_object_type", discriminatorType = DiscriminatorType.CHAR)
public abstract class Flow extends DataSet implements Serializable, IFlowVO {

    public static final String TABLE_NAME = "flow_common";

    /**
     * Serialization ID
     */
    private static final long serialVersionUID = 320361630947897226L;
    /**
     * Synonyms map
     */
    @ElementCollection
    @Column(name = "value", columnDefinition = "TEXT")
    @CollectionTable(name = "flow_synonyms", joinColumns = @JoinColumn(name = "flow_id"))
    @MapKeyColumn(name = "lang")
    protected Map<String, String> synonyms = new HashMap<String, String>();
    /**
     * Adapter for API backwards compatibility.
     */
    @Transient
    private final MultiLangStringMapAdapter synonymsAdapter = new MultiLangStringMapAdapter(new IStringMapProvider() {
        @Override
        public Map<String, String> getMap() {
            return Flow.this.synonyms;
        }
    });
    /**
     * LocationOfSupply map
     */
    @ElementCollection
    @Column(name = "value", columnDefinition = "TEXT")
    @CollectionTable(name = "flow_locationofsupply", joinColumns = @JoinColumn(name = "flow_id"))
    @MapKeyColumn(name = "lang")
    protected Map<String, String> locationOfSupply = new HashMap<String, String>();
    /**
     * Adapter for API backwards compatibility.
     */
    @Transient
    private final MultiLangStringMapAdapter locationOfSupplyAdapter = new MultiLangStringMapAdapter(new IStringMapProvider() {
        @Override
        public Map<String, String> getMap() {
            return Flow.this.locationOfSupply;
        }
    });
    /**
     * The CAS number
     */
    protected String casNumber;

    /**
     * The EC number
     */
    @Column(name = "ecnumber")
    protected String ecNumber;

    /**
     * The sum formula
     */
    protected String sumFormula;

    /**
     * Reference property description
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "reference_property_description_id")
    protected FlowPropertyDescription referencePropertyDescription;

    /**
     * Property descriptions
     */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "flow_propertydescriptions")
    private Set<FlowPropertyDescription> propertyDescriptions = new HashSet<FlowPropertyDescription>();

    /**
     * Cache for the reference property.
     * 20 character limit should be sufficient
     */
    // only for query efficiency
    @Basic
    @Column(name = "referenceProperty_cache", length = 20)
    private String referencePropertyCache;

    /**
     * Cache for the reference property unit.
     * 10 character limit should be sufficient
     */
    // only for query efficiency
    @Basic
    @Column(name = "referencePropertyUnit_cache", length = 10)
    private String referencePropertyUnitCache;


    /**
     * Get the CAS number
     *
     * @return CAS number
     */
    @Override
    public String getCasNumber() {
        return this.casNumber;
    }

    /**
     * Set the CAS number
     *
     * @param casNumber CAS number to set
     */
    public void setCasNumber(String casNumber) {
        this.casNumber = casNumber;
    }

    /**
     * Get the property descriptions
     *
     * @return property descriptions
     */
    public Set<FlowPropertyDescription> getPropertyDescriptions() {
        return this.propertyDescriptions;
    }

    /**
     * Set the property descriptions
     *
     * @param propertyDescriptions property descriptions to set
     */
    protected void setPropertyDescriptions(Set<FlowPropertyDescription> propertyDescriptions) {
        this.propertyDescriptions = propertyDescriptions;
    }

    /**
     * Add a property description
     *
     * @param propertyDescription property description to add
     */
    public void addPropertDesription(FlowPropertyDescription propertyDescription) {
        if (!this.propertyDescriptions.contains(propertyDescription)) {
            this.propertyDescriptions.add(propertyDescription);
        }
    }

    /**
     * Get the reference property description.
     *
     * @return reference property description
     */
    public FlowPropertyDescription getReferencePropertyDescription() {
        return this.referencePropertyDescription;
    }

    /**
     * Get the reference flow property description. Delegates to {@link #getReferencePropertyDescription()}.
     *
     * @return reference flow property description
     */
    @Override
    public FlowPropertyDescription getReferenceFlowProperty() {
        return this.getReferencePropertyDescription();
    }

    /**
     * Set the reference flow property description
     *
     * @param referencePropertyDescription reference property description to set
     */
    public void setReferenceProperty(FlowPropertyDescription referencePropertyDescription) {
        this.referencePropertyDescription = referencePropertyDescription;
    }

    /**
     * Get the sum formula
     *
     * @return sum formula
     */
    @Override
    public String getSumFormula() {
        return this.sumFormula;
    }

    /**
     * Set the sum formula
     *
     * @param sumFormula sum formula to set
     */
    public void setSumFormula(String sumFormula) {
        this.sumFormula = sumFormula;
    }

    /**
     * Get the synonyms
     *
     * @return adapter to synonyms map
     */
    @Override
    public IMultiLangString getSynonyms() {
        return this.synonymsAdapter;
    }

    /**
     * Set the synonyms
     *
     * @param synonyms synonyms to set (adapter writes values to map)
     */
    public void setSynonyms(IMultiLangString synonyms) {
        this.synonymsAdapter.overrideValues(synonyms);
    }

    /**
     * Apply cache fields for flow, those are:
     * <ul>
     * <li>{@link #getReferencePropertyDescription()}</li>
     * <li>{@link FlowPropertyDescription#getDefaultUnit() default unit} of {@link #getReferencePropertyDescription()}</li>
     * </ul>
     */
    @Override
    @PrePersist
    protected void applyDataSetCache() {
        super.applyDataSetCache();
        if (this.referencePropertyDescription != null) {
            if (this.referencePropertyDescription.getFlowPropertyName() != null) {
                this.referencePropertyCache = StringUtils.substring(this.referencePropertyDescription.getFlowPropertyName().getDefaultValue(), 0, 20);
            } else {
                this.referencePropertyCache = null;
            }
            this.referencePropertyUnitCache = StringUtils.substring(this.referencePropertyDescription.getDefaultUnit(), 0, 10);
        } else {
            this.referencePropertyCache = null;
            this.referencePropertyUnitCache = null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetType getDataSetType() {
        return DataSetType.FLOW;
    }

    public abstract TypeOfFlowValue getType();

    public String getEcNumber() {
        return ecNumber;
    }

    public void setEcNumber(String ecNumber) {
        this.ecNumber = ecNumber;
    }

    /**
     * Get the location of supply
     *
     * @return adapter to location of supply
     */
    @Override
    public IMultiLangString getLocationOfSupply() {
        return this.locationOfSupplyAdapter;
    }

    /**
     * Set the location of supply
     *
     * @param locationOfSupply location of supply to set (adapter writes values to map)
     */
    public void setLocationOfSupply(IMultiLangString locationOfSupply) {
        this.locationOfSupplyAdapter.overrideValues(locationOfSupply);
    }

    public String getDirPathInZip() {
        return "ILCD/" + DatasetTypes.FLOWS.getValue();
    }
}

Node/src/main/java/de/iai/ilcd/util/IDatasetListBackingBean.java
package de.iai.ilcd.util;

import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.datastock.IDataStockMetaData;
import de.iai.ilcd.webgui.controller.admin.StockHandler;

public interface IDatasetListBackingBean<E extends DataSet> {

    public StockHandler getStockHandler();

    public DependenciesOptions getDependenciesOptions();

    public IDataStockMetaData getMoveTarget();

    public void setMoveTarget(IDataStockMetaData moveTarget);

}

Node/src/main/webapp/admin/datasets/include/confirmDialog.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf">

	<ui:param name="dialogId" value="#{dataTableId}#{action}Confirm" />
	<p:dialog header="#{dialogHeader}" severity="alert" modal="true"
		widgetVar="#{dialogId}" resizable="false" appendTo="@form">
		<p:ajax event="open"
			listener="#{assignRemoveDataSetHandler.resetForce()}" />
		<p:ajax disabled="#{allMode == 'true' and jobCheckbox == 'false'}"
			event="open" update="@(.#{dataTableId}#{action}panel)"
			listener="#{assignRemoveDataSetHandler.batchNeeded(lazyDataModel, backingBean)}" />

		<div style="padding-top: 15px; padding-bottom: 15px;">
			<h:outputText value="#{dialogMessage}" style="white-space: pre-wrap" />
		</div>

		<h:panelGroup rendered="#{action=='moveSelected'}">
			<div>
				<h:outputText value="#{i18n['admin.stock.move.target']}" />
				<p:spacer width="10px" />
				<p:selectOneMenu value="#{backingBean.moveTarget}"
					converter="#{dsMetaConverter}">
					<f:selectItem itemLabel="#{i18n['common.select.hint']}"
						noSelectionOption="true" />
					<f:selectItems value="#{backingBean.availableStocksForMove}"
						var="stock" itemLabel="#{stock.name}" itemValue="#{stock}" />
				</p:selectOneMenu>
			</div>
			<p:spacer height="10px" />
		</h:panelGroup>

		<ui:include
			src="/admin/datasets/include/dependenciesDropListInclude.xhtml">
			<ui:param name="backingBean" value="#{backingBean}" />
			<ui:param name="showDependenciesOption"
				value="#{showDependenciesOption}" />
		</ui:include>

		<div class="confirmDlgButtons"
			style="display: flex; flex-flow: row wrap; align-items:flex-start; justify-content:space-between;">
			
			<!-- Batch needed checkbox	 -->
			<div style="display:flex; flex-flow:row nowrap; align-items:center; justify-content:flex-start;"
				jsf:rendered="#{jobCheckbox == 'true'}">
				<p:selectBooleanCheckbox
					id="#{dataTableId}#{action}batchNeeded" style="margin: 6px;"
					value="#{assignRemoveDataSetHandler.batchNeeded}">
					<p:ajax update="#{dataTableId}#{action}panel" />
				</p:selectBooleanCheckbox>

				<!-- 	Label of the selectBooleanCheckBox -->
				<!-- 	The element obtained by the label attribut in -->
				<!-- 	p:selectBooleanCheckbox doesn't realign nicely within the surrounding flex box. -->
				<p:outputLabel value="#{i18n['admin.stock.createBatchAsJob']}"/>

				<p:tooltip
					for="#{dataTableId}#{action}batchNeeded" mouseTracking="true"
					adjustX="10" adjustY="20"
					value="Recommended for large datasets, more than 500." />
			</div>
			
			<p:spacer width="20px"/>

			<!-- Cancel + OK buttons -->
			<div style="display:flex; flex-flow:row nowrap; align-items:baseline; justify-content:flex-end;">
				<!-- Cancel button -->
				<c:choose>
					<c:when
						test="#{conf.displayConfig.showDependenciesOptions and showDependenciesOption}">
						<p:commandButton id="#{dialogId}CancelButton"
							value="#{i18n['admin.cancel']}"
							action="#{backingBean.dependenciesOptions.resetDependenciesOption()}"
							oncomplete="PF('#{dialogId}').hide();" />
					</c:when>
					<c:otherwise>
						<p:commandButton
							value="#{i18n['admin.cancel']}"
							onclick="PF('#{dialogId}').hide();" />
					</c:otherwise>
				</c:choose>
				
				
				<!-- Ok button -->
				<h:panelGroup id="#{dataTableId}#{action}panel"
					styleClass="#{dataTableId}#{action}panel">
	
					<p:commandButton id="#{dialogId}OkButton"
						rendered="#{allMode == 'true'}" process="@this" ajax="false"
						value="#{actionDialogOKLabel}"
						action="#{assignRemoveDataSetHandler[action]}" />
	
					<p:commandButton
						rendered="#{allMode != 'true' and not assignRemoveDataSetHandler.batchNeeded}"
						process="@this" ajax="false" value="#{i18n['admin.ok']}"
						action="#{backingBean[action]}" />
	
					<p:commandButton
						rendered="#{assignRemoveDataSetHandler.batchNeeded and jobCheckbox == 'true'}"
						process="@this" ajax="false" value="#{i18n['admin.ok']}"
						action="#{assignRemoveDataSetHandler.batch(lazyDataModel, action)}" />
				</h:panelGroup>
			</div>
		</div>
	</p:dialog>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/contactListInclude.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="datasetListTemplate.xhtml">

	<ui:param name="dataTableId"
		value="#{empty dtId ? 'contactTable' : dtId}" />
	<ui:param name="exportFileName" value="contactTable" />
	<ui:param name="publicShowFacelet" value="showContact" />
	<ui:param name="nameFilterField" value="" />

	<ui:define name="columns">

		<!-- 	classification -->
		<c:set var="id" value="#{'classificationColumn'}" />
		<p:column id="#{id}" exportable="true" toggleable="true"
			style="min-width:100px !important; max-width:200px !important; white-space:pre-line; overflow-wrap:break-word;"
			visible="#{conf.displayConfig.showManageDatasetClassification}">

			<!-- 	COLUMN HEADER -->
			<f:facet name="header">
				<h:outputText id="#{id}HeaderText"
					value="#{i18n['common.dataset.classif']}"
					styleClass="ui-column-title" />
			</f:facet>

			<!-- 	COLUMN CONTENT -->
			<h:outputText id="#{id}ContentClassHierarchyAsString"
				value="#{dataset.classification.classHierarchyAsString}" />
		</p:column>

	</ui:define>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/dependenciesDropListInclude.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:shiro="http://shiro.apache.org/tags"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<h:panelGroup
		rendered="#{conf.displayConfig.showDependenciesOptions and showDependenciesOption}">
		<p:fieldset id = "#{dialogId}Header" legend="#{i18n['admin.advanced.options']}"
			toggleable="true" collapsed="true" style="font-size:75%;">
			<h:panelGrid columns="1" style="margin-bottom:10px" cellpadding="5">
				<h:outputText value="#{i18n['admin.dependencies']}" />
				<p:selectOneRadio layout="pageDirection"
					value="#{backingBean.depOption}"
					converter="#{dependenciesOptionConverter}"
					valueChangeListener="#{backingBean.depOptionChange}">
					<f:selectItems
						value="#{backingBean.dependenciesOptions.dependenciesOptionsValues}"
						var="depOption" itemValue="#{depOption}"
						itemLabel="#{i18n['admin.dependencies.'.concat(depOption)]}" />
				</p:selectOneRadio>
			</h:panelGrid>
		</p:fieldset>
	</h:panelGroup>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/flowListInclude.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="datasetListTemplate.xhtml">

	<ui:param name="dataTableId" value="#{empty dtId ? 'flowTable' : dtId}" />
	<ui:param name="exportedFileName" value="flowTable" />
	<ui:param name="nameFilterField" value="" />

	<ui:define name="columns">

		<!-- 	Type column -->
		<c:set var="id" value="#{'typeColumn'}" />
		<p:column id="#{id}" exportable="true" toggleable="true"
			style="width:100px !important; white-space:pre-line; overflow-wrap:break-word;"
			visible="true">

			<!-- 	COLUMN HEADER -->
			<f:facet name="header">
				<h:outputText id="#{id}HeaderText" value="#{i18n['common.type']}"
					styleClass="ui-column-title" />
			</f:facet>

			<!-- 	COLUMN CONTENT -->
			<h:outputText id="#{id}ContentTypeValue"
				value="#{dataset.type.value}" />
		</p:column>




		<!-- 	classification -->
		<c:set var="id" value="#{'classificationColumn'}" />
		<p:column id="#{id}" exportable="true" toggleable="true"
			style="min-width:100px !important; max-width:200px !important; white-space:pre-line; overflow-wrap:break-word;"
			visible="#{conf.displayConfig.showManageDatasetClassification}">

			<!-- 	COLUMN HEADER -->
			<f:facet name="header">
				<h:outputText id="#{id}HeaderText"
					value="#{i18n['common.dataset.classif']}"
					styleClass="ui-column-title" />
			</f:facet>

			<!-- 	COLUMN CONTENT -->
			<h:outputText id="#{id}ContentClassHierarchyAsString"
				value="#{dataset.classification.classHierarchyAsString}" />
		</p:column>

	</ui:define>
</ui:composition>