Node/src/main/java/de/iai/ilcd/model/flow/Flow.java
package de.iai.ilcd.model.flow;

import de.fzk.iai.ilcd.service.client.impl.DatasetTypes;
import de.fzk.iai.ilcd.service.model.IFlowVO;
import de.fzk.iai.ilcd.service.model.common.IMultiLangString;
import de.fzk.iai.ilcd.service.model.enums.TypeOfFlowValue;
import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.common.DataSetType;
import de.iai.ilcd.util.lstring.IStringMapProvider;
import de.iai.ilcd.util.lstring.MultiLangStringMapAdapter;
import org.apache.commons.lang.StringUtils;

import javax.persistence.*;
import java.io.File;
import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static de.iai.ilcd.model.flow.Flow.TABLE_NAME;

/**
 * Common Flow representation
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = TABLE_NAME, uniqueConstraints = @UniqueConstraint(columnNames = {"UUID", "MAJORVERSION", "MINORVERSION", "SUBMINORVERSION"}))
@DiscriminatorColumn(name = "flow_object_type", discriminatorType = DiscriminatorType.CHAR)
public abstract class Flow extends DataSet implements Serializable, IFlowVO {

    public static final String TABLE_NAME = "flow_common";

    /**
     * Serialization ID
     */
    private static final long serialVersionUID = 320361630947897226L;
    /**
     * Synonyms map
     */
    @ElementCollection
    @Column(name = "value", columnDefinition = "TEXT")
    @CollectionTable(name = "flow_synonyms", joinColumns = @JoinColumn(name = "flow_id"))
    @MapKeyColumn(name = "lang")
    protected Map<String, String> synonyms = new HashMap<String, String>();
    /**
     * Adapter for API backwards compatibility.
     */
    @Transient
    private final MultiLangStringMapAdapter synonymsAdapter = new MultiLangStringMapAdapter(new IStringMapProvider() {
        @Override
        public Map<String, String> getMap() {
            return Flow.this.synonyms;
        }
    });
    /**
     * LocationOfSupply map
     */
    @ElementCollection
    @Column(name = "value", columnDefinition = "TEXT")
    @CollectionTable(name = "flow_locationofsupply", joinColumns = @JoinColumn(name = "flow_id"))
    @MapKeyColumn(name = "lang")
    protected Map<String, String> locationOfSupply = new HashMap<String, String>();
    /**
     * Adapter for API backwards compatibility.
     */
    @Transient
    private final MultiLangStringMapAdapter locationOfSupplyAdapter = new MultiLangStringMapAdapter(new IStringMapProvider() {
        @Override
        public Map<String, String> getMap() {
            return Flow.this.locationOfSupply;
        }
    });
    /**
     * The CAS number
     */
    protected String casNumber;

    /**
     * The EC number
     */
    @Column(name = "ecnumber")
    protected String ecNumber;

    /**
     * The sum formula
     */
    protected String sumFormula;

    /**
     * Reference property description
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "reference_property_description_id")
    protected FlowPropertyDescription referencePropertyDescription;

    /**
     * Property descriptions
     */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "flow_propertydescriptions")
    private Set<FlowPropertyDescription> propertyDescriptions = new HashSet<FlowPropertyDescription>();

    /**
     * Cache for the reference property.
     * 20 character limit should be sufficient
     */
    // only for query efficiency
    @Basic
    @Column(name = "referenceProperty_cache", length = 20)
    private String referencePropertyCache;

    /**
     * Cache for the reference property unit.
     * 10 character limit should be sufficient
     */
    // only for query efficiency
    @Basic
    @Column(name = "referencePropertyUnit_cache", length = 10)
    private String referencePropertyUnitCache;


    /**
     * Get the CAS number
     *
     * @return CAS number
     */
    @Override
    public String getCasNumber() {
        return this.casNumber;
    }

    /**
     * Set the CAS number
     *
     * @param casNumber CAS number to set
     */
    public void setCasNumber(String casNumber) {
        this.casNumber = casNumber;
    }

    /**
     * Get the property descriptions
     *
     * @return property descriptions
     */
    public Set<FlowPropertyDescription> getPropertyDescriptions() {
        return this.propertyDescriptions;
    }

    /**
     * Set the property descriptions
     *
     * @param propertyDescriptions property descriptions to set
     */
    protected void setPropertyDescriptions(Set<FlowPropertyDescription> propertyDescriptions) {
        this.propertyDescriptions = propertyDescriptions;
    }

    /**
     * Add a property description
     *
     * @param propertyDescription property description to add
     */
    public void addPropertDesription(FlowPropertyDescription propertyDescription) {
        if (!this.propertyDescriptions.contains(propertyDescription)) {
            this.propertyDescriptions.add(propertyDescription);
        }
    }

    /**
     * Get the reference property description.
     *
     * @return reference property description
     */
    public FlowPropertyDescription getReferencePropertyDescription() {
        return this.referencePropertyDescription;
    }

    /**
     * Get the reference flow property description. Delegates to {@link #getReferencePropertyDescription()}.
     *
     * @return reference flow property description
     */
    @Override
    public FlowPropertyDescription getReferenceFlowProperty() {
        return this.getReferencePropertyDescription();
    }

    /**
     * Set the reference flow property description
     *
     * @param referencePropertyDescription reference property description to set
     */
    public void setReferenceProperty(FlowPropertyDescription referencePropertyDescription) {
        this.referencePropertyDescription = referencePropertyDescription;
    }

    /**
     * Get the sum formula
     *
     * @return sum formula
     */
    @Override
    public String getSumFormula() {
        return this.sumFormula;
    }

    /**
     * Set the sum formula
     *
     * @param sumFormula sum formula to set
     */
    public void setSumFormula(String sumFormula) {
        this.sumFormula = sumFormula;
    }

    /**
     * Get the synonyms
     *
     * @return adapter to synonyms map
     */
    @Override
    public IMultiLangString getSynonyms() {
        return this.synonymsAdapter;
    }

    /**
     * Set the synonyms
     *
     * @param synonyms synonyms to set (adapter writes values to map)
     */
    public void setSynonyms(IMultiLangString synonyms) {
        this.synonymsAdapter.overrideValues(synonyms);
    }

    /**
     * Apply cache fields for flow, those are:
     * <ul>
     * <li>{@link #getReferencePropertyDescription()}</li>
     * <li>{@link FlowPropertyDescription#getDefaultUnit() default unit} of {@link #getReferencePropertyDescription()}</li>
     * </ul>
     */
    @Override
    @PrePersist
    protected void applyDataSetCache() {
        super.applyDataSetCache();
        if (this.referencePropertyDescription != null) {
            if (this.referencePropertyDescription.getFlowPropertyName() != null) {
                this.referencePropertyCache = StringUtils.substring(this.referencePropertyDescription.getFlowPropertyName().getDefaultValue(), 0, 20);
            } else {
                this.referencePropertyCache = null;
            }
            this.referencePropertyUnitCache = StringUtils.substring(this.referencePropertyDescription.getDefaultUnit(), 0, 10);
        } else {
            this.referencePropertyCache = null;
            this.referencePropertyUnitCache = null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetType getDataSetType() {
        return DataSetType.FLOW;
    }

    public abstract TypeOfFlowValue getType();

    public String getEcNumber() {
        return ecNumber;
    }

    public void setEcNumber(String ecNumber) {
        this.ecNumber = ecNumber;
    }

    /**
     * Get the location of supply
     *
     * @return adapter to location of supply
     */
    @Override
    public IMultiLangString getLocationOfSupply() {
        return this.locationOfSupplyAdapter;
    }

    /**
     * Set the location of supply
     *
     * @param locationOfSupply location of supply to set (adapter writes values to map)
     */
    public void setLocationOfSupply(IMultiLangString locationOfSupply) {
        this.locationOfSupplyAdapter.overrideValues(locationOfSupply);
    }

    public String getDirPathInZip() {
        return "ILCD/" + DatasetTypes.FLOWS.getValue();
    }
}

Node/src/main/java/de/iai/ilcd/model/tag/Tag.java
package de.iai.ilcd.model.tag;

import de.iai.ilcd.model.datastock.AbstractDataStock;
import de.iai.ilcd.model.process.Process;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;


@Entity
@Table(name = "tag")
public class Tag implements Serializable {

    /**
     * Serialization ID
     */
    private static final long serialVersionUID = -8653425645726217710L;
    @ManyToMany(mappedBy = "tags")
    protected Set<Process> processes = new HashSet<Process>();
    @ManyToMany(mappedBy = "tags")
    protected Set<AbstractDataStock> ds = new HashSet<AbstractDataStock>();
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "name")
    private String name;
    @Column(name = "description")
    private String description;
    private boolean visible = false;

    public Tag() {
        super();
    }

    public Tag(String name) {
        if (name == null)
            throw new NullPointerException("Provided tag name was null.");
        this.name = name;
    }

    /**
     * @return the ID of Tag
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the ID of Tag to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the processes
     */
    public Set<Process> getProcesses() {
        return processes;
    }

    /**
     * @param processes the processes to set
     */
    public void setProcesses(Set<Process> processes) {
        this.processes = processes;
    }

    /**
     * @return the ds
     */
    public Set<AbstractDataStock> getDs() {
        return ds;
    }

    /**
     * @param ds the ds to set
     */
    public void setDs(Set<AbstractDataStock> ds) {
        this.ds = ds;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    public boolean containedInList(List<Tag> tagList) {
        for (Tag t : tagList) {
            if (name.equals(t.getName()))
                return true;
        }
        return false;
    }

    public boolean isVisible() {
        return this.visible;
    }

    public void setVisible(boolean value) {
        this.visible = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        Tag tag = (Tag) o;
//		if (tag.name == null || name == null)
        return Objects.equals(name, tag.name);
//
//		return Objects.equals(name.toLowerCase(Locale.ROOT), tag.name.toLowerCase(Locale.ROOT));
    }

    @Override
    public int hashCode() {
//		if (name == null)
        return Objects.hash(null);
//		return Objects.hash(name.toLowerCase(Locale.ROOT));
    }
}

Node/src/main/webapp/datasetdetail/include/backLinks.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--
via ui:param:
	- linkDetailOutcome
	- linkListOutcome
	- linkValue
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:soda="http://java.sun.com/jsf/composite/sodacomp">
	
	<div id="backLinks">
		#{utilStr['unicodeChar.blackLeftPointer']}&#160;<h:link outcome="#{linkDetailOutcome}" value="#{i18n['common.backTo']} #{linkValue}#{i18n['delimiter']}#{i18n['public.dataset.datasetOverviewPage']}" />
		<span style="white-space:pre">&#09;</span>
		#{utilStr['unicodeChar.blackLeftPointer']}&#160;<h:link outcome="#{linkListOutcome}" value="#{i18n['common.backTo']} #{linkValue}#{i18n['delimiter']}#{i18n['public.datasets']}" />
		<span style="white-space:pre">&#09;</span>
		#{utilStr['unicodeChar.blackLeftPointer']}&#160;<h:link outcome="#{url.index}" value="#{i18n['common.backTo']} #{conf.applicationTitle}" />
		<span style="white-space:pre">&#09;</span>
	</div>
</ui:composition>

Node/src/main/webapp/datasetdetail/include/classNameLevel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--
used in
	- contact.xhtml
	- flowproperty.xhtml
	- lciamethod.xhtml
	- process_info.xhtml
	- source.xhtml
	- unitgroup.xhtml
	- NOT in flow.xhtml => special version: classification and categorization

via ui:param:
	- xmlClassification
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:soda="http://java.sun.com/jsf/composite/sodacomp">
	
	<div>
		<soda:outputTextTooltip
			outputTextId="className"
			outputTextValue="#{i18n['common.className']}"
			tooltipValue="#{i18n['datasetdetail.tooltip.dataset.className']}"
			inline="true" />
		<h:outputText value=": " />
		<soda:outputTextTooltip
			outputTextId="classLevel"
			outputTextValue="#{i18n['common.hierarchyLevel']}"
			tooltipValue="#{i18n['datasetdetail.tooltip.dataset.classLevel']}"
			inline="true" />
	</div>
	<soda:dataListStyled dataListValue="#{xmlClassification}">
		<ui:param name="class" value="#{dataListStyledVar}" />
		#{class.name}:
		<ui:fragment rendered="#{DataSetType.PROCESS == process.dataSetType}">
			<h:outputText rendered="#{class.name.equalsIgnoreCase('OEKOBAU.DAT')}" value="#{processHandler.getLastElementOfList(class.clazz).classId} " />
		</ui:fragment>
		<h:outputText value="#{processHandler.getClassTypeListInline(class.clazz, class.name, lang)}" />
	</soda:dataListStyled>
</ui:composition>

Node/src/main/webapp/datasetdetail/include/compliance.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--
short version of compliance declarations
used in
	- flow.xhtml
	- flowproperty.xhtml
	- unitgroup.xhtml

via ui:param:
	- xmlCompliances
	- handler
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:soda="http://java.sun.com/jsf/composite/sodacomp">

	<ui:repeat value="#{xmlCompliances}" var="compliance">
		<p:panelGrid columns="3">
			#{i18n['common.compliance']}
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="referenceToComplianceSystem"
						outputTextValue="#{i18n['common.referenceToComplianceSystem']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.referenceToComplianceSystem']}" />
				</div>
				<soda:dataListLinkOrText
					dataListValue="#{handler.getMultilangWithFallback(lang, compliance.referenceToComplianceSystem.shortDescription)}"
					outputLinkValue="#{handler.getReferenceUrlXml(compliance.referenceToComplianceSystem, url.source)}"
					outputLinkTitle="#{i18n['common.source.inflected']}#{i18n['delimiter']}#{i18n['public.dataset']}" />
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="approvalOfOverallCompliance"
						outputTextValue="#{i18n['common.approvalOfOverallCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.approvalOfOverallCompliance']}" />
				</div>
				<span class="italic">#{compliance.approvalOfOverallCompliance.value}</span>
			</h:panelGroup>
		</p:panelGrid>
	</ui:repeat>
</ui:composition>

Node/src/main/webapp/datasetdetail/include/complianceAll.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--
full version of compliance declarations
used in
	- lciamethod.xhtml
	- process_modelValid.xhtml

via ui:param:
	- xmlCompliances
	- handler
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:soda="http://java.sun.com/jsf/composite/sodacomp">

	<ui:repeat value="#{xmlCompliances}" var="compliance">
		<p:panelGrid columns="8">
			#{i18n['common.compliance']}
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="referenceToComplianceSystem"
						outputTextValue="#{i18n['common.referenceToComplianceSystem']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.referenceToComplianceSystem']}" />
				</div>
				<soda:dataListLinkOrText
					dataListValue="#{handler.getMultilangWithFallback(lang, compliance.referenceToComplianceSystem.shortDescription)}"
					outputLinkValue="#{handler.getReferenceUrlXml(compliance.referenceToComplianceSystem, url.source)}"
					outputLinkTitle="#{i18n['common.source.inflected']}#{i18n['delimiter']}#{i18n['public.dataset']}" />
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="approvalOfOverallCompliance"
						outputTextValue="#{i18n['common.approvalOfOverallCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.approvalOfOverallCompliance']}" />
				</div>
				<span class="italic">#{compliance.approvalOfOverallCompliance.value}</span>
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="nomenclatureCompliance"
						outputTextValue="#{i18n['common.nomenclatureCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.nomenclatureCompliance']}" />
				</div>
				<span class="italic">#{compliance.nomenclatureCompliance.value}</span>
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="methodologicalCompliance"
						outputTextValue="#{i18n['common.methodologicalCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.methodologicalCompliance']}" />
				</div>
				<span class="italic">#{compliance.methodologicalCompliance.value}</span>
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="reviewCompliance"
						outputTextValue="#{i18n['common.reviewCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.reviewCompliance']}" />
				</div>
				<span class="italic">#{compliance.reviewCompliance.value}</span>
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="documentationCompliance"
						outputTextValue="#{i18n['common.documentationCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.documentationCompliance']}" />
				</div>
				<span class="italic">#{compliance.documentationCompliance.value}</span>
			</h:panelGroup>
			<h:panelGroup>
				<div>
					<soda:outputTextTooltip
						outputTextId="qualityCompliance"
						outputTextValue="#{i18n['common.qualityCompliance']}"
						tooltipValue="#{i18n['datasetdetail.tooltip.dataset.qualityCompliance']}" />
				</div>
				<span class="italic">#{compliance.qualityCompliance.value}</span>
			</h:panelGroup>
		</p:panelGrid>
	</ui:repeat>
</ui:composition>

Node/src/main/webapp/datasetdetail/include/listTags.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--
via ui:param:
	- showInvisibleTags
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:soda="http://java.sun.com/jsf/composite/sodacomp">

	<p:repeat var="tag" varStatus="tagStatus" value="#{(not empty showInvisibleTags and showInvisibleTags) ? processHandler.process.associatedTagsList : processHandler.process.visibleTagsList}">
		<!-- h:panelGroup wrapper for nested conditions -->
		<h:panelGroup rendered="#{conf.displayConfig.showTagsHorizontally}">
			<h:panelGroup rendered="#{conf.displayConfig.showTagName}">
				<soda:outputTextTooltip outputTextId="tagText"
					outputTextValue="#{tag.name.concat(conf.displayConfig.tagsDelimiter)}"
					tooltipValue="#{tag.description}" 
					rendered="#{!tagStatus.last}" />
				<soda:outputTextTooltip outputTextId="tagText"
					outputTextValue="#{tag.name}"
					tooltipValue="#{tag.description}" 
					rendered="#{tagStatus.last}" />
			</h:panelGroup>
			<h:panelGroup rendered="#{!conf.displayConfig.showTagName}">
				<soda:outputTextTooltip outputTextId="tagText"
					outputTextValue="#{tag.description.concat(conf.displayConfig.tagsDelimiter)}"
					tooltipValue="#{tag.name}"
					rendered="#{!tagStatus.last}" />
				<soda:outputTextTooltip outputTextId="tagText"
					outputTextValue="#{tag.description}"
					tooltipValue="#{tag.name}"
					rendered="#{tagStatus.last}" />
			</h:panelGroup>
		</h:panelGroup>
		<h:panelGroup rendered="#{!conf.displayConfig.showTagsHorizontally}">
			<h:panelGroup rendered="#{conf.displayConfig.showTagName}">
				<soda:outputTextTooltip outputTextId="tagText"
					outputTextValue="#{tag.name}"
					tooltipValue="#{tag.description}" />
				<br/>
			</h:panelGroup>
			<h:panelGroup rendered="#{!conf.displayConfig.showTagName}">
				<soda:outputTextTooltip outputTextId="tagText"
					outputTextValue="#{tag.description}"
					tooltipValue="#{tag.name}" />
				<br/>
			</h:panelGroup>
		</h:panelGroup>
	</p:repeat>
</ui:composition>

Node/src/main/webapp/datasetdetail/include/otherVersionsAvailableStaticMessage.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets">
                
<!--                 Informs user of existing superceding data set or newer versions. 						-->
<!--                 ui:params: 																			-->
<!--                 	handler - ProcessHandler 															-->
<!--                 	detailsView - Boolean. True directs links to external/detail pages of data sets. 	-->
    
<!--     Alert if superceding data set exists or more recent version exists. Prefer superceding data set alert. -->
	<p>
		<p:staticMessage rendered="#{handler.supersedingVersion != null}" severity="warn"
	         		detail="#{i18n['common.dataset.supercedingDataSetExists']}"/>
		<p:staticMessage rendered="#{handler.supersedingVersion == null and !handler.mostRecentVersion}" severity="warn"
	     			detail="#{i18n['common.dataset.newerVersionExists']}."/>
	</p>
	
<!-- 	Always provide prominent link to superceding data set (newest version). -->
	<p>
		<h:form rendered="#{handler.supersedingVersion != null}">
			<h:outputLink rendered="#{!detailsView}" value="#{conf.contextPath}#{urlgen.getDetail(handler.supersedingVersion)}">
				<h:outputText value="#{i18n['common.dataset.viewSupercedingDataSet']}" />
			</h:outputLink>
			<h:outputLink rendered ="#{detailsView and !handler.foreignDataSet}" value="#{conf.contextPath}#{urlgen.getResourceDetailHtml(handler.supersedingVersion)}">
				<h:outputText value="#{i18n['common.dataset.viewSupercedingDataSet']}"/>
			</h:outputLink>
			<h:outputLink rendered ="#{detailsView and handler.foreignDataSet}" value="#{urlgen.getDetail(handler.supersedingVersion)}">
				<h:outputText value="#{i18n['common.dataset.viewSupercedingDataSet']}"/>
			</h:outputLink>
		</h:form>
	</p>
	
<!-- 	Provide prominent link to most recent version and links to other versions. -->
	<p>
		<h:form rendered="#{handler.otherVersionPresent}" style="display:inline">
			<h:form rendered="#{!handler.mostRecentVersion}" style="display:inline">
				<h:outputText value="#{i18n['common.dataset.mostRecentVersion']}:" />
				<p:spacer width="5"/>
				<h:outputLink rendered="#{!detailsView}" value="#{conf.contextPath}#{urlgen.getDetail(handler.getNewerVersion())}">
					<h:outputText value="#{handler.getNewerVersion().version}"/>
				</h:outputLink>
				<h:outputLink rendered="#{detailsView and !handler.foreignDataSet}"
						value="#{conf.contextPath}#{urlgen.getResourceDetailHtml(handler.getNewerVersion())}" style="color:blue">
					<h:outputText value="#{handler.getNewerVersion().version}"/>
				</h:outputLink>
				<h:outputLink rendered="#{detailsView and handler.foreignDataSet}" value="#{urlgen.getDetail(handler.getNewerVersion())}"
						style="color:blue">
					<h:outputText value="#{handler.getNewerVersion().version}"/>
				</h:outputLink>
				<p:spacer width="10"/>
			</h:form>
<!-- 							other versions -->
			<h:form rendered="#{!detailsView and not empty handler.otherVersionsWithoutMostRecentVersion}" style="display:inline">
				<h:outputText value="#{i18n['public.dataset.otherVersions']}:" />
				<ui:repeat value="#{handler.otherVersionsWithoutMostRecentVersion}" var="ov">
					<p:spacer width="5"/>
					<h:outputLink value="#{conf.contextPath}#{urlgen.getDetail(ov)}">
						<h:outputText value="#{ov.version}"/>
					</h:outputLink>
				</ui:repeat>
			</h:form>
		</h:form>
	</p>
</ui:composition>