Node/src/main/java/de/iai/ilcd/model/adapter/dataset/AbstractDatasetAdapter.java
package de.iai.ilcd.model.adapter.dataset;

import de.fzk.iai.ilcd.service.client.impl.vo.dataset.DataSetVO;
import de.fzk.iai.ilcd.service.model.IDataSetListVO;
import de.fzk.iai.ilcd.service.model.IDataSetVO;
import de.iai.ilcd.model.adapter.ClassificationAdapter;
import de.iai.ilcd.model.adapter.LStringAdapter;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public abstract class AbstractDatasetAdapter<T extends DataSetVO, LVO extends IDataSetListVO, VO extends IDataSetVO> {

    @SuppressWarnings("unused")
    private static final Logger logger = LogManager.getLogger(AbstractDatasetAdapter.class);

    private final T dataset;

    protected String language = null;

    protected boolean langFallback = false;

    private AbstractDatasetAdapter(T adapterObject) {
        this.dataset = adapterObject;
    }

    public AbstractDatasetAdapter(T adapterObject, LVO adaptee) {
        this(adapterObject);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    public AbstractDatasetAdapter(T adapterObject, VO adaptee) {
        this(adapterObject);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    private AbstractDatasetAdapter(T adapterObject, String language) {
        this(adapterObject, language, false);
    }

    private AbstractDatasetAdapter(T adapterObject, String language, boolean langFallback) {
        this.dataset = adapterObject;
        this.language = language;
        this.langFallback = langFallback;
    }

    public AbstractDatasetAdapter(T adapterObject, LVO adaptee, String language) {
        this(adapterObject, adaptee, language, false);
    }

    public AbstractDatasetAdapter(T adapterObject, LVO adaptee, String language, boolean langFallback) {
        this(adapterObject, language, langFallback);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    public AbstractDatasetAdapter(T adapterObject, VO adaptee, String language) {
        this(adapterObject, language);
        this.copyValues(adaptee);
        this.copyValues(adaptee, this.dataset);
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Copy the values from the value <b>AND</b> the list value object
     * to the adapter data set.
     *
     * @param src source object
     * @param dst destination data set
     */
    protected abstract void copyValues(VO src, T dst);

    /**
     * Copy the values from the list value object
     * to the adapter data set
     *
     * @param src source object
     * @param dst destination data set
     */
    protected abstract void copyValues(LVO src, T dst);

    private final void copyValues(IDataSetVO src) {
        this.copyValues((IDataSetListVO) src);
        LStringAdapter.copyLStrings(src.getDescription(), this.dataset.getDescription(), this.language, this.langFallback);
    }

    private final void copyValues(IDataSetListVO src) {

        this.dataset.setUuid(src.getUuidAsString());
        this.dataset.setDataSetVersion(src.getDataSetVersion());
        this.dataset.setPermanentUri(src.getPermanentUri());

        LStringAdapter.copyLStrings(src.getName(), this.dataset.getName(), this.language, this.langFallback);

        try {
            this.dataset.setClassification(new ClassificationAdapter(src.getClassification()));
        } catch (Exception e) {
        }

        this.dataset.setSourceId(src.getSourceId());
        this.dataset.setHref(src.getHref());

        if (src.getDuplicates().size() > 0)
            this.dataset.setDuplicates(src.getDuplicates());
    }

    public T getDataSet() {
        return dataset;
    }

    public boolean isLangFallback() {
        return langFallback;
    }

    public void setLangFallback(boolean langFallback) {
        this.langFallback = langFallback;
    }

}

Node/src/main/java/de/iai/ilcd/model/flow/Flow.java
package de.iai.ilcd.model.flow;

import de.fzk.iai.ilcd.service.client.impl.DatasetTypes;
import de.fzk.iai.ilcd.service.model.IFlowVO;
import de.fzk.iai.ilcd.service.model.common.IMultiLangString;
import de.fzk.iai.ilcd.service.model.enums.TypeOfFlowValue;
import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.common.DataSetType;
import de.iai.ilcd.util.lstring.IStringMapProvider;
import de.iai.ilcd.util.lstring.MultiLangStringMapAdapter;
import org.apache.commons.lang.StringUtils;

import javax.persistence.*;
import java.io.File;
import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static de.iai.ilcd.model.flow.Flow.TABLE_NAME;

/**
 * Common Flow representation
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = TABLE_NAME, uniqueConstraints = @UniqueConstraint(columnNames = {"UUID", "MAJORVERSION", "MINORVERSION", "SUBMINORVERSION"}))
@DiscriminatorColumn(name = "flow_object_type", discriminatorType = DiscriminatorType.CHAR)
public abstract class Flow extends DataSet implements Serializable, IFlowVO {

    public static final String TABLE_NAME = "flow_common";

    /**
     * Serialization ID
     */
    private static final long serialVersionUID = 320361630947897226L;
    /**
     * Synonyms map
     */
    @ElementCollection
    @Column(name = "value", columnDefinition = "TEXT")
    @CollectionTable(name = "flow_synonyms", joinColumns = @JoinColumn(name = "flow_id"))
    @MapKeyColumn(name = "lang")
    protected Map<String, String> synonyms = new HashMap<String, String>();
    /**
     * Adapter for API backwards compatibility.
     */
    @Transient
    private final MultiLangStringMapAdapter synonymsAdapter = new MultiLangStringMapAdapter(new IStringMapProvider() {
        @Override
        public Map<String, String> getMap() {
            return Flow.this.synonyms;
        }
    });
    /**
     * LocationOfSupply map
     */
    @ElementCollection
    @Column(name = "value", columnDefinition = "TEXT")
    @CollectionTable(name = "flow_locationofsupply", joinColumns = @JoinColumn(name = "flow_id"))
    @MapKeyColumn(name = "lang")
    protected Map<String, String> locationOfSupply = new HashMap<String, String>();
    /**
     * Adapter for API backwards compatibility.
     */
    @Transient
    private final MultiLangStringMapAdapter locationOfSupplyAdapter = new MultiLangStringMapAdapter(new IStringMapProvider() {
        @Override
        public Map<String, String> getMap() {
            return Flow.this.locationOfSupply;
        }
    });
    /**
     * The CAS number
     */
    protected String casNumber;

    /**
     * The EC number
     */
    @Column(name = "ecnumber")
    protected String ecNumber;

    /**
     * The sum formula
     */
    protected String sumFormula;

    /**
     * Reference property description
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "reference_property_description_id")
    protected FlowPropertyDescription referencePropertyDescription;

    /**
     * Property descriptions
     */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "flow_propertydescriptions")
    private Set<FlowPropertyDescription> propertyDescriptions = new HashSet<FlowPropertyDescription>();

    /**
     * Cache for the reference property.
     * 20 character limit should be sufficient
     */
    // only for query efficiency
    @Basic
    @Column(name = "referenceProperty_cache", length = 20)
    private String referencePropertyCache;

    /**
     * Cache for the reference property unit.
     * 10 character limit should be sufficient
     */
    // only for query efficiency
    @Basic
    @Column(name = "referencePropertyUnit_cache", length = 10)
    private String referencePropertyUnitCache;


    /**
     * Get the CAS number
     *
     * @return CAS number
     */
    @Override
    public String getCasNumber() {
        return this.casNumber;
    }

    /**
     * Set the CAS number
     *
     * @param casNumber CAS number to set
     */
    public void setCasNumber(String casNumber) {
        this.casNumber = casNumber;
    }

    /**
     * Get the property descriptions
     *
     * @return property descriptions
     */
    public Set<FlowPropertyDescription> getPropertyDescriptions() {
        return this.propertyDescriptions;
    }

    /**
     * Set the property descriptions
     *
     * @param propertyDescriptions property descriptions to set
     */
    protected void setPropertyDescriptions(Set<FlowPropertyDescription> propertyDescriptions) {
        this.propertyDescriptions = propertyDescriptions;
    }

    /**
     * Add a property description
     *
     * @param propertyDescription property description to add
     */
    public void addPropertDesription(FlowPropertyDescription propertyDescription) {
        if (!this.propertyDescriptions.contains(propertyDescription)) {
            this.propertyDescriptions.add(propertyDescription);
        }
    }

    /**
     * Get the reference property description.
     *
     * @return reference property description
     */
    public FlowPropertyDescription getReferencePropertyDescription() {
        return this.referencePropertyDescription;
    }

    /**
     * Get the reference flow property description. Delegates to {@link #getReferencePropertyDescription()}.
     *
     * @return reference flow property description
     */
    @Override
    public FlowPropertyDescription getReferenceFlowProperty() {
        return this.getReferencePropertyDescription();
    }

    /**
     * Set the reference flow property description
     *
     * @param referencePropertyDescription reference property description to set
     */
    public void setReferenceProperty(FlowPropertyDescription referencePropertyDescription) {
        this.referencePropertyDescription = referencePropertyDescription;
    }

    /**
     * Get the sum formula
     *
     * @return sum formula
     */
    @Override
    public String getSumFormula() {
        return this.sumFormula;
    }

    /**
     * Set the sum formula
     *
     * @param sumFormula sum formula to set
     */
    public void setSumFormula(String sumFormula) {
        this.sumFormula = sumFormula;
    }

    /**
     * Get the synonyms
     *
     * @return adapter to synonyms map
     */
    @Override
    public IMultiLangString getSynonyms() {
        return this.synonymsAdapter;
    }

    /**
     * Set the synonyms
     *
     * @param synonyms synonyms to set (adapter writes values to map)
     */
    public void setSynonyms(IMultiLangString synonyms) {
        this.synonymsAdapter.overrideValues(synonyms);
    }

    /**
     * Apply cache fields for flow, those are:
     * <ul>
     * <li>{@link #getReferencePropertyDescription()}</li>
     * <li>{@link FlowPropertyDescription#getDefaultUnit() default unit} of {@link #getReferencePropertyDescription()}</li>
     * </ul>
     */
    @Override
    @PrePersist
    protected void applyDataSetCache() {
        super.applyDataSetCache();
        if (this.referencePropertyDescription != null) {
            if (this.referencePropertyDescription.getFlowPropertyName() != null) {
                this.referencePropertyCache = StringUtils.substring(this.referencePropertyDescription.getFlowPropertyName().getDefaultValue(), 0, 20);
            } else {
                this.referencePropertyCache = null;
            }
            this.referencePropertyUnitCache = StringUtils.substring(this.referencePropertyDescription.getDefaultUnit(), 0, 10);
        } else {
            this.referencePropertyCache = null;
            this.referencePropertyUnitCache = null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetType getDataSetType() {
        return DataSetType.FLOW;
    }

    public abstract TypeOfFlowValue getType();

    public String getEcNumber() {
        return ecNumber;
    }

    public void setEcNumber(String ecNumber) {
        this.ecNumber = ecNumber;
    }

    /**
     * Get the location of supply
     *
     * @return adapter to location of supply
     */
    @Override
    public IMultiLangString getLocationOfSupply() {
        return this.locationOfSupplyAdapter;
    }

    /**
     * Set the location of supply
     *
     * @param locationOfSupply location of supply to set (adapter writes values to map)
     */
    public void setLocationOfSupply(IMultiLangString locationOfSupply) {
        this.locationOfSupplyAdapter.overrideValues(locationOfSupply);
    }

    public String getDirPathInZip() {
        return "ILCD/" + DatasetTypes.FLOWS.getValue();
    }
}

Node/src/main/java/de/iai/ilcd/webgui/controller/admin/DatasetRegistrationSummaryBean.java
package de.iai.ilcd.webgui.controller.admin;

import de.iai.ilcd.model.process.Process;
import de.iai.ilcd.model.registry.Registry;
import de.iai.ilcd.rest.RegistryService;
import de.iai.ilcd.webgui.util.Consts;
import eu.europa.ec.jrc.lca.commons.rest.dto.DataSetRegistrationResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Component("datasetRegistrationSummaryBean")
@Scope("view")
public class DatasetRegistrationSummaryBean implements Serializable {

    private static final long serialVersionUID = -3144746029685291342L;

    @Autowired
    private RegistryService registryService;

    private Registry registry;

    private int accepted;

    private int rejected;

    private int errorCount;

    private List<Process> rejectedProcesses;

    private List<Process> rejectedCompliance;

    private List<Process> rejectedNoDifference;

    private List<Process> errorList;

    private boolean isGLAD = false;

    @PostConstruct
    private void init() {
        List<DataSetRegistrationResult> result = (List<DataSetRegistrationResult>) FacesContext.getCurrentInstance().getExternalContext().getFlash().get(
                Consts.REGISTRATION_RESULT);

        List<Process> processes = (List<Process>) FacesContext.getCurrentInstance().getExternalContext().getFlash().get(Consts.SELECTED_DATASETS);

        Long registryId = (Long) FacesContext.getCurrentInstance().getExternalContext().getFlash().get(Consts.SELECTED_REGISTRY);

        if (registryId != -1)
            registry = registryService.findById(registryId);
        else
            isGLAD = true;
        displaySummaryMessage(processes, result);
    }

    private void displaySummaryMessage(List<Process> datasets, List<DataSetRegistrationResult> result) {

        rejectedCompliance = groupBy(DataSetRegistrationResult.REJECTED_COMPLIANCE, result, datasets);

        rejectedNoDifference = groupBy(DataSetRegistrationResult.REJECTED_NO_DIFFERENCE, result, datasets);

        errorList = groupBy(DataSetRegistrationResult.ERROR, result, datasets);

        if (!isGLAD) {
            rejected = rejectedCompliance.size() + rejectedNoDifference.size();
            errorCount = errorList.size();
            accepted = result.size() - rejected - errorCount;
        } else {
            rejected = rejectedCompliance.size() + rejectedNoDifference.size() + errorList.size();
            accepted = result.size() - rejected;
        }

        rejectedProcesses = new ArrayList<>(rejectedNoDifference);
        rejectedProcesses.addAll(rejectedCompliance);
        rejectedProcesses.addAll(errorList);
    }

    private List<Process> groupBy(DataSetRegistrationResult regResult, List<DataSetRegistrationResult> result, List<Process> datasets) {
        List<Process> grouped = new ArrayList<>();
        for (int i = 0; i < result.size(); i++) {
            if (result.get(i) == regResult) {
                grouped.add(datasets.get(i));
            }
        }
        return grouped;
    }

    public Registry getRegistry() {
        return registry;
    }

    public int getAccepted() {
        return accepted;
    }

    public int getRejected() {
        return rejected;
    }

    public int getErrorCount() {
        return errorCount;
    }

    public List<Process> getRejectedProcesses() {
        return rejectedProcesses;
    }

    public List<Process> getRejectedCompliance() {
        return rejectedCompliance;
    }

    public List<Process> getRejectedNoDifference() {
        return rejectedNoDifference;
    }

    public List<Process> getErrorList() {
        return errorList;
    }

    public boolean isRejectedCompliance(Process process) {
        return rejectedCompliance.contains(process);
    }

    public boolean isRejectedNoDifference(Process process) {
        return rejectedNoDifference.contains(process);
    }

    public boolean isError(Process process) {
        return errorList.contains(process);
    }

    public boolean isGlad() {
        return isGLAD;
    }
}

Node/src/main/webapp/admin/datasets/datasetRegistrationSummary.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:body>
	<ui:composition template="/admin/layout/adminDesign.xhtml">
		<ui:param name="pageTitle" value="#{i18n['admin.datasetRegistrationSummary.title']}" />
		<ui:define name="content">
			<h:form id="generalForm" prependId="false">
				<p:panel header="#{i18n['admin.datasetRegistrationSummary.title']}" >
					<h:panelGrid columns="2"
						columnClasses="column1of4,column2of4"
						styleClass="detailsWidth" >
						
						<h:outputLabel value="#{i18n['admin.datasetRegistrationSummary.registry']}:" for="registryName" rendered="#{datasetRegistrationSummaryBean.registry!=null}"/>
						<h:outputText id="registryName"
							value="#{datasetRegistrationSummaryBean.registry.name}" rendered="#{datasetRegistrationSummaryBean.registry!=null}"/>

						<h:outputLabel value="#{datasetRegistrationSummaryBean.glad ? i18n['admin.datasetRegistrationSummary.success'] : i18n['admin.datasetRegistrationSummary.approved']}:"
							for="accepted" />
						<h:outputText id="accepted"
							value="#{datasetRegistrationSummaryBean.accepted}" />

						<h:outputLabel value="#{datasetRegistrationSummaryBean.glad ? i18n['admin.datasetRegistrationSummary.notRegistered'] : i18n['admin.datasetRegistrationSummary.rejected']}:"
							for="rejected" />
						<h:outputText id="rejected"
							value="#{datasetRegistrationSummaryBean.rejected}" />
							
						<h:outputLabel value="#{i18n['admin.datasetRegistrationSummary.error']}:"
							for="error" rendered="#{!datasetRegistrationSummaryBean.glad}"/>
						<h:outputText id="error"
							value="#{datasetRegistrationSummaryBean.errorCount}" rendered="#{!datasetRegistrationSummaryBean.glad}"/>	
					</h:panelGrid>
				</p:panel>
				
				<p:panel header="#{datasetRegistrationSummaryBean.glad ? i18n['admin.datasetRegistrationSummary.notRegisteredDataSets'] : i18n['admin.datasetRegistrationSummary.rejectedDataSets']}" > <!-- rendered="#{datasetRegistrationSummaryBean.registry!=null}" -->
					<p:dataTable id="processTable" var="process"
						value="#{datasetRegistrationSummaryBean.rejectedProcesses}" paginator="true"
						rows="15" lazy="false" rowsPerPageTemplate="5,10,15,50"
						paginatorTemplate="{CurrentPageReport} {FirstPageLink}
			                     {PreviousPageLink} {PageLinks} {NextPageLink}
			                     {LastPageLink} {RowsPerPageDropdown} #{i18n['common.list.entriesPerPage']}"
				        currentPageReportTemplate="#{i18n['common.list.currentEntries']}: {totalRecords} 
		    		    		 		 (#{dataSetsRegistrationBean.count} #{i18n['common.list.total']})  
		        		 			 (#{i18n['common.list.page']} {currentPage} #{i18n['common.list.of']} {totalPages})"
						emptyMessage="#{i18n['common.list.noneFound']}">
						
						<p:column headerText="#{i18n['common.name']}" sortBy="#{process.name.value}" filterBy="#{process.name.value}" filterMatchMode="contains">
							<h:outputText value="#{process.name.value}" />
						</p:column>

						<p:column headerText="#{i18n['admin.proc.version']}" sortBy="#{process.version}" filterBy="#{process.version}">
							<h:outputText value="#{process.version}" />
						</p:column>

						<p:column headerText="#{i18n['common.type']}" sortBy="#{process.type.value}" filterBy="#{process.type.value}">
							<h:outputText value="#{process.type.value}" />
						</p:column>

						<p:column headerText="#{i18n['common.dataset.classif']}" sortBy="#{process.classification.classHierarchyAsString}" 
							filterBy="#{process.classification.classHierarchyAsString}" filterMatchMode="contains">
							<h:outputText value="#{process.classification.classHierarchyAsString}" />
						</p:column>
						
						<p:column headerText="#{datasetRegistrationSummaryBean.glad ? i18n['admin.datasetRegistrationSummary.reason'] : i18n['admin.datasetRegistrationSummary.rejectionReason']}">
							<h:outputText value="#{datasetRegistrationSummaryBean.glad ? i18n['admin.datasetRegistrationSummary.invalidDataSet'] : i18n['admin.datasetRegistrationSummary.invalidCompliance']}" 
								rendered="#{datasetRegistrationSummaryBean.isRejectedCompliance(process)}"/>
							<h:outputText value="#{i18n['admin.datasetRegistrationSummary.noDifference']}" 
								rendered="#{datasetRegistrationSummaryBean.isRejectedNoDifference(process)}"/>
							<h:outputText value="#{i18n['admin.datasetRegistrationSummary.errorReason']}" 
								rendered="#{datasetRegistrationSummaryBean.isError(process)}"/>
						</p:column>
						
					</p:dataTable>
				</p:panel>
				
			</h:form>
			<ui:include src="/messages.xhtml" />
		</ui:define>
	</ui:composition>
</h:body>
</html>


Node/src/main/webapp/admin/datasets/registerDatasets.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:body>
	<ui:composition template="/admin/layout/adminDesign.xhtml">
		<ui:param name="pageTitle" value="#{i18n['admin.registerDataSets.title']}" />
		<ui:define name="content">
			<h:outputText value="#{dataSetsRegistrationBean.count} #{i18n['admin.registerDataSets.toBeRegistered']}"/>
			<h:form id="generalForm" prependId="false" rendered="#{applicationInfoBean.showRegistrationControls}">
				<h:panelGroup id="dsPanel">
					<p:dataTable id="processTable" var="process"
						value="#{dataSetsRegistrationBean.processes}" paginator="true"
						rows="15" lazy="false" rowsPerPageTemplate="5,10,15,50,#{dataSetsRegistrationBean.count > 50 ? dataSetsRegistrationBean.count : null}"
						paginatorTemplate="{CurrentPageReport} {FirstPageLink}
			                     {PreviousPageLink} {PageLinks} {NextPageLink}
			                     {LastPageLink} {RowsPerPageDropdown} #{i18n['common.list.entriesPerPage']}"
				        currentPageReportTemplate="#{i18n['common.list.currentEntries']}: {totalRecords} 
		    		    		 		 (#{dataSetsRegistrationBean.count} #{i18n['common.list.total']})  
		        		 			 (#{i18n['common.list.page']} {currentPage} #{i18n['common.list.of']} {totalPages})"
						rowStyleClass="#{dataSetsRegistrationBean.isRegistered(process) ? 'registered' : null}"
						emptyMessage="#{i18n['common.list.noneFound']}"
						sortMode="multiple">

						<p:column headerText="#{i18n['common.uuid']}" sortBy="#{process.uuidAsString}" filterBy="#{process.uuidAsString}">
							<h:outputText value="#{process.uuidAsString}" />
						</p:column>
						
						<p:column headerText="#{i18n['common.name']}" sortBy="#{process.name.value}" filterBy="#{process.name.value}" filterMatchMode="contains">
							<h:outputText value="#{process.name.value}" />
						</p:column>

						<p:column headerText="#{i18n['public.proc.version']}" sortBy="#{process.version}" filterBy="#{process.version}">
							<h:outputText value="#{process.version}" />
						</p:column>

						<p:column headerText="#{i18n['common.type']}" sortBy="#{process.type.value}" filterBy="#{process.type.value}">
							<h:outputText value="#{process.type.value}" />
						</p:column>

						<p:column headerText="#{i18n['common.dataset.classif']}" sortBy="#{process.classification.classHierarchyAsString}" 
							filterBy="#{process.classification.classHierarchyAsString}" filterMatchMode="contains">
							<h:outputText
								value="#{process.classification.classHierarchyAsString}" />
						</p:column>

						<p:column headerText="#{i18n['common.dataset.location']}" sortBy="#{process.geography.location}" filterBy="#{process.geography.location}">
							<h:outputText value="#{process.geography.location}" />
						</p:column>

						<p:column headerText="#{i18n['common.dataset.refYear']}" sortBy="#{process.timeInformation.referenceYear}" filterBy="#{process.timeInformation.referenceYear}">
							<h:outputText value="#{process.timeInformation.referenceYear}" />
						</p:column>

						<p:column headerText="#{i18n['common.proc.validUntilYear']}" sortBy="#{process.timeInformation.validUntil}" filterBy="#{process.timeInformation.validUntil}">
							<h:outputText value="#{process.timeInformation.validUntil}" />
						</p:column>
					</p:dataTable>
				</h:panelGroup>

				<p:panel id="selectRegistryPanel"
					header="#{i18n['admin.registerDataSets.registry']}">
					<h:panelGrid columns="2">
						<h:outputLabel value="#{i18n['admin.registerDataSets.registerIn']} #{i18n['common.markMandatory']}:"
							for="reg" />
						<h:selectOneMenu id="reg"
							value="#{dataSetsRegistrationBean.registry}">
							<f:selectItems value="#{registriesIdsSelectItems.items}" />
							<p:ajax event="valueChange" process="@this" update="dsPanel" />	
						</h:selectOneMenu>
					</h:panelGrid>
				</p:panel>

				<div class="buttonCenter">
					<p:commandButton value="#{i18n['admin.registerDataSets.registerButton']}" id="btnRegister"
						update="messages" action="#{dataSetsRegistrationBean.register}" ajax="false"/>
				</div>

			</h:form>
			<ui:include src="/messages.xhtml" />
		</ui:define>
	</ui:composition>
</h:body>
</html>
